import Foundation

enum ProductCatalog {
    static let championColorNamesByCode: [String: String] = [
        "000": "White",
        "1045": "Blue Breeze",
        "1103": "Wildflower Pale Blue",
        "1149": "New Aqua",
        "1616": "Light Blue",
        "1818": "Royal",
        "190": "Navy",
        "1914": "Athletic Navy",
        "2009": "Cargo Olive",
        "2106": "Emerald Green",
        "232": "Teal",
        "234": "Kelly Green",
        "256": "Dark Green",
        "2702": "Marine Green",
        "2707": "Marine Green",
        "285": "Field Green",
        "338": "Yellow Cab",
        "373": "Vegas Gold",
        "377": "C Gold",
        "4111": "Spirited Orange",
        "465": "Orange",
        "475": "Texas Orange",
        "5113": "Lilac Pink",
        "5116": "Truthful Pink",
        "529": "Scarlet",
        "536": "Classic Red",
        "539": "Cardinal",
        "5395": "Bright Cardinal",
        "578": "Maroon",
        "588": "Garnet",
        "6017": "Urban Lilac",
        "6026": "Regal Purple",
        "630": "Purple",
        "680": "Purple",
        "6801": "Dark Purple",
        "695": "Deep Purple",
        "7004": "Ivory Canvas",
        "7010": "Cocoa Butter",
        "7091": "Oatmeal",
        "7162": "Latte",
        "7163": "Tantalizing Tan",
        "7202": "Briefly Brown",
        "740": "White Alabaster",
        "7403": "Chalk White",
        "775": "Brown",
        "780": "Western Brown",
        "798": "Pebblestone",
        "9022": "Manhattan Mist",
        "9030": "Silver Opal",
        "9032": "Concrete Gray",
        "930": "Heather Grey",
        "939": "Active Grey",
        "940": "Silver Grey",
        "948": "Gunsmoke",
        "950": "Oxford Grey",
        "955": "Heritage Grey",
        "972": "Graphite",
        "990": "Granite Heather",
        "9901": "Granite",
        "999": "Black"
    ]

    static let gearColorNamesByCode: [String: String] = [
        "000": "White",
        "007": "Winter White",
        "1029": "Dungaree Blue",
        "1034": "Nighttime Iris",
        "1135": "Dark Nilas",
        "1151": "Windy Blue",
        "1300": "Creek Blue",
        "1301": "Cobalt Blue Glass",
        "1322": "Clean Slate Blue",
        "1616": "Light Blue",
        "1818": "Royal",
        "181T": "Royal Triblend",
        "190": "Navy",
        "2078": "Portal Teal",
        "2102": "Dry Moss Green",
        "2309": "Thermal Green",
        "2606": "Aqua Tonic",
        "2811": "Out Field",
        "285": "Field Green",
        "310": "Butter",
        "3302": "Amber Yellow",
        "373": "Vegas Gold",
        "390": "Pencil Gold",
        "4111": "Spirited Orange",
        "4203": "Peach Melon",
        "465": "Orange",
        "475": "Texas Orange",
        "5311": "Clay Rose",
        "536": "Classic Red",
        "5366": "Chalk Red",
        "5430": "Rose Tea",
        "5554": "Barn Red",
        "560": "Cardinal",
        "578": "Maroon",
        "588": "Garnet",
        "6020": "PeriBlue",
        "623": "Frosty Lavender",
        "630": "Purple",
        "7091": "Oatmeal Heather",
        "7101": "Cafe Au Lait",
        "7160": "Mushroom",
        "775": "Brown",
        "779": "Brown Sepia",
        "9033": "Crystal Grey",
        "906": "Faded Black",
        "910": "Iced Heather",
        "9120": "Silver Filigree",
        "921": "Salt & Pepper Heather",
        "948": "Gunsmoke Heather",
        "950": "Oxford Heather",
        "990": "Charcoal Heather",
        "999": "Black"
    ]

    static let comfortWashColorNamesByCode: [String: String] = [
        "5A": "Athletic Red",
        "A60B": "Artisan Gold",
        "ACUO": "Rich Green Grass",
        "AN3D": "Parchment",
        "ANJL": "Future Lavender",
        "AP5J": "Latte Brown",
        "APGB": "Porch Blue",
        "H6F": "Crimson Fall",
        "H6G": "Coral Craze",
        "H6H": "Summer Squash",
        "H6I": "Cypress",
        "H6K": "Mint",
        "H6Q": "Soothing Blue",
        "H6R": "Anchor Slate",
        "H6S": "Summer Sky",
        "H6T": "Deep Forte",
        "H66": "New Railroad",
        "H67": "Concrete",
        "HBK": "Black",
        "HBE3": "Garnet",
        "HEN": "Cayenne",
        "HHF": "Horizon Orange",
        "HMR": "Maroon",
        "HNY": "Navy",
        "HSXE": "Cotton Candy",
        "HTX": "Texas Orange",
        "HWF": "White",
        "HWOC": "Freshwater",
        "HWP": "Mauve",
        "HWR": "Saltwater",
        "MS": "Moss",
        "O9N": "Field Green",
        "PZ": "Grape Soda",
        "XBC": "Ocean Depths"
    ]

    static let comfortWashStyleNumbers: Set<String> = [
        "GDH100",
        "GDH125",
        "GDH135",
        "GDH150",
        "GDH175",
        "GDH200",
        "GDH250",
        "GDH275",
        "GDH280",
        "GDH300",
        "GDH400",
        "GDH425",
        "GDH450",
        "GDH475",
        "GDH480"
    ]

    static let colorNamesByCode = championColorNamesByCode
        .merging(gearColorNamesByCode) { champion, _ in champion }
        .merging(comfortWashColorNamesByCode) { existing, _ in existing }

    static let knownColorCodes = Set(championColorNamesByCode.keys)
        .union(gearColorNamesByCode.keys)
        .union(comfortWashColorNamesByCode.keys)
}
